### ISSUE TITLE
Some questions about the current file / folder structure (v0.4.0)

### ISSUE THREAD

**Issue by BePo65** [g-mero/esday#22]
1. why is `format.ts` in 'src/core/impl' but `parseDate.ts` in 'src/core'? For a consistent structure, `parseDate.ts` should be renamed to `parse.ts` and moved to `src/core/impl`.

2. `constant.ts` should be named as plural (`constants.ts`), as this file contains several constants.

3. `unit.ts` should IMHO also be spelled as plural, as it contains several unit types. In the current structure, the unit constants from `constant.ts` (from 'MS' to 'Date') could also be moved to `units.ts` without violating the naming scheme.

4. as the constants from `src/common/index.ts` are very often imported as `import * as C from constant`, why not export all constants as default export (in addition to the existing named exports). This would make the import avoid the wildcard (`import C from constant`.
Besides this, as you know already, I prefer "speaking" names and `C` says nothing to me 😄

**Comment by g-mero** [comment]
The constant already exported as C in common/index.ts. And I agree with you about 1-3. It's helpful if you can provide a pr about those.

**Comment by BePo65** [comment]
concerning '4':
the question was, if we shouldn't create a default export already in 'constant.ts'.
This way the '* as C' (which I only see for used js-only dependencies) in 'index.ts' could be replaced with 'import C from constant.ts'.

**Comment by g-mero** [comment]
It's reasonable for me. You could request a pr.
