### ISSUE TITLE
Remarks on using commit-and-tag-version

### ISSUE THREAD

**Issue by BePo65** [g-mero/esday#25]
commit-and-tag-version creates a changelog and updates the version of the package. The new version number is based on the messages of the commits since the last version following this approach:

- if one of the commit messages contains "BREAKING CHANGE" in the footer, then a new major version is created ('x.0.0'), otherwise
- if one of the commit messages starts with "feat: ", then a new minor version is created ('a.x.0'), otherwise
- if one of the commit messages starts with "fix: ", then a new patch version is created ('a.b.x')

Especially during the first development phase (before the first official 1.0.0 release) it may be required to manually set the version number. This can be done by using the '--release-as' option. An example could be

```
pnpm run release -- --release-as 0.5.0
```

For more details see the [readme](https://github.com/absolute-version/commit-and-tag-version?tab=readme-ov-file#release-as-a-target-type-imperatively-npm-version-like) of absolute-version/commit-and-tag-version.

**Comment by g-mero** [comment]
Thanks for reminding me of that.
