### ISSUE TITLE
Which reference to use in tests

### ISSUE THREAD

**Issue by BePo65** [g-mero/esday#26]
In the tests for the utc plugin, this project uses `dayjs` to compare results to. A quite clever way to avoid e.g. problems with current locale.

The details of `esday` are not in all respects the same as dayjs (e.g. concerning the plugin structure) and dayjs still has a long list of open pr concerning differences between dayjs and momentjs or errors in dayjs. And the objective of dayjs is to be a 100% compatible replacement of momentjs.

So wouldn't it be better to use momentjs as a reference for tests?

**Comment by g-mero** [comment]
I agree.
