### ISSUE TITLE
Support locales

### ISSUE THREAD

**Issue by BePo65** [g-mero/esday#5]
In dayjs i18n is supported in the form of a mechanism similar to the plugin concept (see [dayjs documentation](https://day.js.org/docs/en/i18n/i18n). Basically the locales are objects conforming to a defined interface.

In the next branch of dayjs I implemented this concept based on typescript.

```
// From https://stackoverflow.com/questions/41139763/how-to-declare-a-fixed-length-array-in-typescript
type Tuple<
  T,
  N extends number,
  R extends readonly T[] = []
> = R['length'] extends N ? R : Tuple<T, N, readonly [T, ...R]>

export type DayNames<T = string> = Tuple<T, 7>
export type MonthNames<T = string> = Tuple<T, 12>
export type MonthNamesFunction<T = MonthNames<string>> = {
  (format: string): string
  standalone: T
  format: T
}
export type RelativeTimeElementFunction = (
  timeValue: string | number,
  withoutSuffix: boolean,
  range: string
) => string

type Format =
  | 'LT'
  | 'LTS'
  | 'L'
  | 'LL'
  | 'LLL'
  | 'LLLL'
  | 'l'
  | 'll'
  | 'lll'
  | 'llll'
type Relative =
  | 'future'
  | 'past'
  | 's'
  | 'm'
  | 'mm'
  | 'h'
  | 'hh'
  | 'd'
  | 'dd'
  | 'M'
  | 'MM'
  | 'y'
  | 'yy'

// Type definition of locale (usually a literal object)
export interface Locale {
  name: string
  weekdays: DayNames
  weekdaysShort?: DayNames
  weekdaysMin?: DayNames
  months: MonthNames | MonthNamesFunction
  monthsShort?: MonthNames | MonthNamesFunction
  ordinal?: (number: string, period?: 'W') => string
  weekStart?: number
  yearStart?: number
  formats?: Partial<Record<Format, string>>
  relativeTime?: Record<Relative, string | RelativeTimeElementFunction>
  meridiem?: (hour: number, minute: number, isLowercase: boolean) => string
  invalidDate?: string
}
```

The only point I'm not sure about is the fact that in this implementation all properties of the interface `Locale` are optional.
+ this way you can easily change only those properties that differ from the default language (i.e. english),
+ but if I look at the pr in the dayjs repository, then there are (too) many definitions for Locales that are missing some properties. As a result, parsing or formatting may create unexpected results.

So today I would make all properties mandatory, to make clear that they are required and readonly to prevent inadvertent changes.

All those Locales could be positioned in a folder named `locales` (to be consistent with the plugins).

I prepared pr for (extended) parsing and formatting - not yet uploaded. To complete these tests, I would need at least the default locale ('en').
I'm not sure, if all methods do already support locales. If they do, adding more locales should be easy using the code form the dayjs next branch (supporting the locales 'af', 'en', 'ja', 'rn', 'th' and of course 'zh-cn').

**Comment by g-mero** [comment]
Yes, I agree with you. 

Actually I’ve removed all locale-related code from the core format method and the customParseFormat plugin (such as 'MMM' or 'dd' rely on locales) for fully separating core and locals.  So I think maybe we should move the locale system into a dedicated plugin, such as advancedFormat or localizedFormat. And create a new `localizedParse` plugin ? I'm not decided yet.

**Comment by BePo65** [comment]
Ah,I understand what you mean.

There are 2 different parts of localization:
1. the implementation
2. the required configurations

My code snippet above was about the second part (how to define the required data that make up a Locale). And here every Locale must be defined in a file of its own and IMHO stored in a folder of its own.

What you are talking about is the first part. In that respect dayjs is not consistently enough: some localization elements are defined in the core implementation (i.e. "MMM") and some are implemented in plugins (i.e. CustomParseFormat and AdvancedFormat).

So for sure it is a very good idea to put all these elements in plugins; and IMHO separating parsing from formatting would make sense too.

But then we have functions like `startOf` and `endOf` that depend on the Locale too (for the unit 'week'). That is not parsing and not formatting.

As a consequence we need at least a minimal definition for the current Locale containing the `weekStart` property in the core module. That should not be too much of a problem; in the interface `Locale` above, all properties besides `weekStart` must be optional (and we have to live with incomplete configurations) or we define a union type with 2 parts consisting of the minimal set and the complete set.

Anyway I should not add tests for the locale dependent tags to my parsing and formatting tests.

Does this all help you to come to a decision?

**Comment by BePo65** [comment]
Just one more remark: I've tried to collect all tags that depend on the Locale. Am I missing one?

| Tag    | Out-/Input | Description |
| ------ | ---------- | ----------- |
| MMM | Jan-Dec | The abbreviated month name |
| MMMM | January-December | The full month name |
| dd | Su-Sa | The min name of the day of the week |
| ddd | Sun-Sat | The short name of the day of the week |
| dddd | Sunday-Saturday | The name of the day of the week |
| Do | 1st... 31st | Day of Month with ordinal |
| A | AM PM | The meridians of a time in uppercase |
| a | am pm | The meridians of a time in lowercase |
| w | 1 2 ... 52 53 | The week of the year |
| ww | 01 02 ... 52 53 | The week of year, 2-digits  |
| LT | 8:02 PM | The short form for "h:mm A" |
| LTS | 8:02:18 PM | The short form for "h:mm:ss A" |
| L | 08/16/2018 | The short form for "MM/DD/YYYY" |
| LL | August 16, 2018 | The short form for "MMMM D, YYYY" |
| LLL | August 16, 2018 8:02 PM | The short form for "MMMM D, YYYY h:mm A" |
| LLLL | Thursday, August 16, 2018 8:02 PM | The short form for "dddd, MMMM D, YYYY h:mm A" |
| l | 8/16/2018 | The short form for "M/D/YYYY" |
| ll | Aug 16, 2018 | The short form for "MMM D, YYYY" |
| lll | Aug 16, 2018 8:02 PM | The short form for "MMM D, YYYY h:mm A" |
| llll | Thu, Aug 16, 2018 8:02 PM | The short form for "ddd, MMM D, YYYY h:mm A" |

**Comment by g-mero** [comment]
I believe you covered all the tags.

I've implemented the `startOf ` and `endOf ` methods already (see: https://github.com/g-mero/esday/blob/main/src/core/Impl/startOf.ts). Does the `week` unit depends on the Locale? I didn't notice that during my implementation.

**Comment by BePo65** [comment]
startOf / endOf and format are the to elements I am just working on additional tests. Trying to find out how to get these tests independent of the current locale and this on linux and windows is quite an interesting topic 😄.

The start of the week differs in different parts of the world - for more details see [What Is the First Day of the Week?](https://www.timeanddate.com/calendar/days/first-day-of-the-week.html)

Besides that: can it be that you never sleep? At least it looks so to me 😄

**Comment by g-mero** [comment]
You're right, I overlooked that. I think I should consider adding an internal $locale in EsDay.

It's midday here in China—I just woke up, I stayed up too late last night.

**Comment by g-mero** [comment]
@BePo65 what's yout opinion of #10

**Comment by BePo65** [comment]
Please give me 1 or 2 days: I am just working on extended tests for startOf / endOf that would improve the test coverage. I hope that these tests make validating your changes easier. Besides this, I hope to get a deeper understanding of the details of EsDay etc.
