### ISSUE TITLE
Push tags for published versions to github

### ISSUE THREAD

**Issue by BePo65** [g-mero/esday#7]
I saw that there are 7 published versions on [npmjs](https://www.npmjs.com/package/esday?activeTab=versions), but here on github there are no tags defined.

IMHO the state of the project a release is based on should be tagged with that version number (i.g. using a `v0.1.0` tag).

I am sure, your local repository contains those tags. So would you please push these tags to github?

**Comment by g-mero** [comment]
Because I was urgently using this library in one of my own projects, I overlooked creating any local tags. I’ll make sure to include tags in future releases.

**Comment by BePo65** [comment]
How about using [commit-and-tag-version](https://www.npmjs.com/package/commit-and-tag-version)?

I use it in my projects in combination with [@commitlint/cli](https://www.npmjs.com/package/@commitlint/cli) to automatically create a new version of a package by setting the version field in package.json and creating a changelog file all based on the commit messages.

@commitlint/cli makes sure that the commit messages are usable for this procedure.

What I like on commit-and-tag-version is the fact that it does not automatically publish to npmjs. So I can verify the generated version and the changelog and modify the data if I don't like the results.

If you are interested, I can deliver a setup as a pr.

**Comment by g-mero** [comment]
I’d be happy to accept the PR.

**Comment by g-mero** [comment]
pr merged #12
